### ISSUE TITLE
Alert when shard goes down 

### ISSUE THREAD

**Issue by zumo64** [redis-field-engineering/redis-enterprise-grafana-dashboards#12]
We have a client that experienced a shard loss without any standard redis provided Prometheus alerts firing.

I tested the alert below that requires shards ids  (master shards) - it works but requires hard coded values 
Maybe that can be improved to be made generic 

```
- alert: Shard went down 
    expr: absent(redis_up{job="redis-enterprise", status="active", redis="42"}) == 1 or absent(redis_up{job="redis-enterprise", status="active", redis="39" }) == 1
    for: 20s
    labels:
      severity: critical
    annotations:
      description: "Shard is down  - Cluster: {{ $labels.cluster }} Shard: {{$labels.redis}} Node: {{$labels.node}} Database:{{$labels.bdb}}"

```
